baseURL: "https://mshore-dev.github.io/"
title: "Michael's Blog"
theme: "PaperMod"

params:
  env: "production"
  homeInfoParams:
    Title: "Michael Shore"
    Content: "Aspiring sysadmin, studying Networking and Cybersecurity at Finger Lakes Community College."

  socialIcons:
    - name: github
      url: "https://github.com/mshore-dev"
    - name: linkedin
      url: "https://www.linkedin.com/in/michael-shore-7489a11b7/"
    - name: email
      url: "mailto:iam@mshore.dev"
